version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo
    env_file: ./.env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}   